name: quality
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - notebook>=6
  - jupyter
  - erddapy
  - httpx
  - ioos_qc
  - bokeh
  - pandas
  - python-dateutil
  - netCDF4
  - matplotlib
  - shapely
  - pyproj